# Made by RandomHashTags
messages:
  receive loot from Equipment Lootbox: # Broadcasted
  - "&6&l(!)&r &6{PLAYER} received a {ITEM}&r &6from a Equipment Lootbox!"
  #
  cannot apply:
    armor set piece:
      - "&c&l(!)&r &cYou cannot apply an Armor Set Crystal to an existing Armor Set piece!"
    already has crystal:
      - "&c&l(!)&r &cYou cannot apply multiple Armor Set crystals to a single piece of gear!"
#
items:
  equipment lootbox:
    item: "chest"
    name: "&6&lEquipment Lootbox&r &7(Right Click)"
    lore:
    - " "
    - "&7&nRight-click&r &7to receive a random"
    - "&7item from one of these armor sets!"
    - " "
    - "&6&lAvailable Armor Sets"
    - " &6&l*&r &c&lPhantom Armor Set"
    - " &6&l*&r &b&lYeti Armor Set"
    - " &6&l*&r &f&lMother Of Yijki Armor Set"
    - " &6&l*&r &a&lRanger Armor Set"
    - " &6&l*&r &4&lSupreme Armor Set"
    - " &6&l*&r &5&lDimensional Traveler Armor Set"
    reveal amount: 1
    reveal display: 8 # Amount of seconds for the rewards to be shown, and the randomization stops
    gui:
      title: "&lEquipment Lootbox"
      size: 9
      background:
        item: "stained_glass_pane:7"
        name: " "
      slots: "4"
    rewards:
      - "customarmor:PHANTOM:random"
      - "customarmor:YETI:random"
      - "customarmor:YIJKI:random"
      - "customarmor:RANGER:random"
      - "customarmor:SUPREME:random"
      - "customarmor:TRAVELER:random"
  heroic upgrade:
    item: "yellow_dye"
    name: "&6&lHeroic&r &6({NAME}&r&6) &lUpgrade"
    lore:
      - " "
      - "&7Apply to any {NAME}&r &7armor"
      - "&7for a &6{PERCENT}% &7chance to imbue it"
      - "&7with the power of Heroic Armor!"
      - " "
      - "&7This will increase the armor's base"
      - "&7stats as well as add a &612.5% negation"
      - "&7to enemy &6Infinite Luck &7enchantments."
    attributes:
      - ""
  crystal:
    item: "nether_star"
    name: "&6&lArmor Crystal (&r{NAME}&r&6&l)"
    lore:
    - "&a{PERCENT}% Success Rate"
    - "&7Can be applied to any non"
    - "&7armor set that is not"
    - "&7already equipped with a"
    - "&7bonus crystal to gain"
    - "&7a passive advantage!"
    - " "
    - "&6&lCrystal Bonus:"
    - " {NAME}"
    - "{PERKS}"
    applied lore: "&6&lArmor Crystal (&r{NAME}&r&6&l)"
  omni crystal:
    item: "snowball"
    name: "&3&lOmni Crystal (&r&7{PERCENT}&3&l)"
    lore:
      - "&7Apply to any non-specialty"
      - "&7weapon or armor piece to"
      - "&7transform it into an &3&nOmni Item:"
      - "&7An item that acts as any"
      - "&7unique /help armorset piece."
      - " "
      - "&3EX: &71 Omni item, 3 Phantom items equipped"
      - "&7would apply the Phantom Set Bonus to player."
    applied lore:
      - " "
      - "&3&lOMNI SET BONUS"
      - "&3&l*&r &3Acts as ANY Armor Set type/piece."
      - " "
#
heroic:
  added lore:
    - " "
    - "&7+{ARMOR_VALUE} Armor Value"
    - "&7{DURABILITY} Durability"
    - "&4+{BONUS_ATTACK_DMG} Bonus Attack Damage"
    - "&4This armor is stronger than diamond."
  default armor value:
    helmet: 3
    chestplate: 8
    leggings: 6
    boots: 3
  default durability:
    helmet: 810
    chestplate: 1000
    leggings: 935
    boots: 686
    sword: 1952
    axe: 1952
  default bonus attack damage:
    sword: 4
  #
  helmet:
    item: "leather_helmet"
    name: "&3&lGhostly Hood&r {ENCHANT_SIZE}"
    lore:
    - "VEnchants{Protection4;Unbreaking3}"
    - "RPEnchants{Valor;Angelic;Tank;Armored;Drunk;Implants;Arrow Deflect;Death God;Resilience;Protection;Frozen}"
    - "{Immortal}:chance=40"
  chestplate:
    item: "leather_chestplate"
    name: "&3&lGhostly Shroud&r {ENCHANT_SIZE}"
    lore:
    - "SetArmorValue{8}"
    - "SetDurability{1000}"
  leggings:
    item: "leather_leggings"
    name: "&3&lGhostly Robes&r {ENCHANT_SIZE}"
  boots:
    item: "leather_boots"
    name: "&3&lGhostly Whisp"
  sword:
    item: "golden_sword"
#