# Made by RandomHashTags
messages:
  on cooldown:
    - "&c&l(!)&r &cThis trinket is on cooldown! You can use its ability again in {TIME}."
#
global attributes:
  - "isDamaged;VictimIsInList=TRINKET_ANTI_PROJECTILE_FORCEFIELD;VictimIsProjectile;SetDamage=dmg*0.5"