# Made by RandomHashTags
reveal item:
  item: "book"
  name: "&d&lHeroic Enchantment Book &7(Right Click)"
  lore:
  - "&7Examine to receive a random"
  - "&dheroic &7enchantment book."
#
reveals enchant rarities: "HEROIC"
reveal enchant msg:
- "&e&l(!) &eYou examine the &d&lHeroic Enchantment Book..."
- "&eand discovered {ENCHANT}"
#
revealed item:
  item: "book"
  name colors: "&d&l&n"
  apply colors: "&d"
  firework: "ball:red:fuchsia:3"
#
settings:
  success+destroy=100: false
  #
  success: "&a{PERCENT}% Success Rate"
  destroy: "&c{PERCENT}% Destroy Rate"
  lore format:
  - "{SUCCESS}"
  - "{DESTROY}"
  - "{ENCHANT_LORE}"
  - "{ENCHANT_TYPE}"
  - "&7Drop onto item to enchant"
#