# Made by RandomHashTags
file system:
  enabled: false
  type: LOCAL/MYSQL
  host: localhost
  port: 3306
  database: GlobalBase
  username: user
  password: password
#
supported plugins:
  standalone:
    PlaceholderAPI: true
  mechanics:
    SilkSpawners: true
    EpicSpawners: true
    MCMMO Classic/Overhaul: true
  regional:
    FactionsUUID: true
    ASkyblock: false
    SuperiorSkyblock: false
#
chat cmds:
  # {F_TAG}
  ## = If the player is in a faction --> The player's relation color to recipient + The player's faction role + The player's faction tag + a space
  ## = Player isn't in a faction --> nothing
  # {DISPLAYNAME} = The player's display name
  # {MESSAGE} = The sent message
  # {TITLE} = The player's formatted active title. If one is active, a space is added before it.
  format: "{F_TAG}{DISPLAYNAME}{TITLE}&r: {MESSAGE}"
  brag:
    enabled: true
    hover message: "&7Click to view &n{PLAYER}&r&7's inventory!"
    display: "&6&o{PLAYER}'s Inventory&r"
    invalid:
      - "&cInvalid!"
    no perm:
      - "&cYou do not have permission to link items in chat with [BRAG]!"
      - "&7Purchase a rank at &nbuy.yourserver.com&r &7and try again!"
  item:
    enabled: true
    display: "\u00BB &r{ITEM_NAME} &7({ITEM_AMOUNT}x) &f\u00AB&r "
    no perm:
      - "&cYou do not have permission to link items in chat with [ITEM]!"
      - "&7Purchase a rank at &nbuy.yourserver.com&r &7and try again!"
#
backup interval: 360 # Measured in minutes
#
alchemist:
  enabled: true
  cmds:
    - alchemist
#
auction house:
  enabled: true
  cmds:
    - auctionhouse
    - ah
    - auction
#
balance:
  enabled: true
  cmds:
    - balance
    - bal
#
bless:
  enabled: true
  cmds:
    - bless
#
boosters:
  enabled: true
#
bump:
  enabled: true
  cmds:
    - bump
#
coinflip:
  enabled: true
  cmds:
    - coinflip
    - cf
#
combine:
  enabled: true
  cmds:
    - combine
#
confirm:
  enabled: true
  cmds:
    - confirm
#
collection filter:
  enabled: true
  cmds:
    - collectionfilter
#
conquest:
  enabled: true
  cmds:
    - conquest
#
custom armor:
  enabled: true
#
custom bosses:
  enabled: true
#
custom enchants:
  enabled: true
  #
  black scrolls: true
  enchantment orbs: true
  fireballs: true
  randomization scrolls: true
  rarity gems: true
  soul trackers: true
  transmog scrolls: true
  white scrolls: true
#
custom creepers:
  enabled: true
#
custom tnt:
  enabled: true
#
disabled enchants:
  enabled: true
  cmds:
    - disabledenchants
#
duels:
  enabled: false
  cmds:
    - duel
    - duels
#
dungeons:
  enabled: false
  cmds:
    - dungeon
    - dungeons
#
enchants:
  enabled: true
  cmds:
    - enchants
  #
  format: "{ENCHANT}&r &7[Level 1-{MAX}]"
  description color: "&7"
  hover:
    - "&7&nTier"
    - "{TIER}"
    - " "
    - "&7&nDescription"
    - "{DESC}"
  msg:
    - " "
    - "&b&lEnchantment Guide (&r&d&l{PAGE}&r&b&l/&r&d&l{MAX_PAGE}&r&b&l)"
    - " "
    - "{ENCHANTS}"
    - " "
    - "&e&l(!)&r &eHover over and Enchantment to learn more about it."
    - "&7Use &n/enchants <page>&r &7to browse other enchantments."
    - " "
#
enchanter:
  enabled: true
  cmds:
    - enchanter
#
envoy:
  enabled: true
  cmds:
    - envoy
#
faction upgrades:
  enabled: true
  cmds:
    - f upgrade
#
fund:
  enabled: true
  cmds:
    - fund
#
gkits:
  enabled: true
  cmds:
    - gkit
    - gkits
#
global challenges:
  enabled: true
  cmds:
    - globalchallenge
    - globalchallenges
    - challenges
#
home:
  enabled: true
  cmds:
    - home
    - homes
#
item filter:
  enabled: true
  cmds:
    - filter
#
jackpot:
  enabled: true
  cmds:
    - jackpot
#
kingofthehill:
  enabled: true
  cmds:
    - kingofthehill
    - koth
#
last man standing:
  enabled: false
  cmds:
    - lastmanstanding
    - lms
    - warzone
#
lootboxes:
  enabled: true
  cmds:
    - lootbox
    - lootboxes
#
masks:
  enabled: true
#
mkits:
  enabled: true
  cmds:
    - mkit
    - mkits
#
mob stacker:
  enabled: true
#
monthly crates:
  enabled: true
  cmds:
    - monthlycrate
    - monthlycrates
    - cc
    - mc
#
outposts:
  enabled: false
  cmds:
    - outpost
    - outposts
#
pets:
  enabled: false
#
player quests:
  enabled: true
  cmds:
    - quest
    - quests
#
wild pvp:
  enabled: true
  cmds:
    - wildpvp
    - pvp
#
raid events:
  enabled: true
  cmds:
    - raid
#
roll:
  enabled: true
  cmds:
    - roll
#
server crates:
  enabled: true
#
shop:
  enabled: true
  cmds:
    - shop
#
showcase:
  enabled: true
  cmds:
    - showcase
#
spawner stacking:
  enabled: true
#
splitsouls:
  enabled: true
  cmds:
    - splitsouls
#
randompackage: # Not disableable
  cmds:
    - rp
#
tinkerer:
  enabled: true
  cmds:
    - tinkerer
#
title:
  enabled: true
  cmds:
    - title
    - titles
#
trade:
  enabled: true
  cmds:
    - trade
#
trinkets:
  enabled: false
#
vkits:
  enabled: true
  cmds:
    - vkit
    - vkits
#
wild:
  enabled: false
  cmds:
    - wild
#
withdraw:
  enabled: true
  cmds:
    - withdraw
#
xpbottle:
  enabled: true
  cmds:
    - xpbottle
#
no permission:
  - "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is an error."
#