# Made by RandomHashTags
messages:
  not enough money:
    - "&c&l(!)&r &cYou do not have enough $ to unlock that dungeon key!"
    - "&c&lCOST&r &f${PRICE}"
#
settings:
  portals:
    # Spawnable locations: SAFEZONE, WARZONE, FACTION, WILDERNESS, ANYWHERE
    spawnable: "safezone"
#
master:
  title: "Dungeons Master"
  size: 9
  #
  purchase lore:
    - " "
    - "&7Purchase this  key to unlock access"
    - "&7to the associated dungeon."
    - " "
    - "&7Please note that you will still"
    - "&7need to craft/find a &ndungeon portal"
    - "&7each time you wish to run this dungeon."
    - " "
  #
  abandoned spaceship key:
    slot: 0
    price: 25000000
    item: "tripwire_hook"
    name: "&5&l&nAbandoned Spaceship Key"
    lore:
      - "&c&lCOST&r &f${PRICE}"
#
gui:
  title: "Server Dungeons"
  size: 45
  background:
    item: "black_stained_glass_pane"
    name: " "
  undiscovered:
    dungeon:
      item: "stained_glass_pane:1:1;name{&6&l???}"
      lore:
        - "&7This dungeon has not"
        - "&7been discovered yet."
    key:
      item: "red_stained_glass_pane"
      name: "&c&l???"
      lore:
        - "&7The key to this dungeon"
        - "&7cannot be obtained yet."
  #
  info:
    slot: 3
    item: "book"
    name: "&c&l&nServer Dungeons"
    lore:
      - "&7Dungeons are &ntop tier PvE instances"
      - "&7for the most powerful players to conquer."
      - " "
      - "&7Filled with &cadvanced custom AI"
      - "&7and unique challenges, these maps"
      - "&7will puch any Serveonaut to the limit."
      - " "
      - "&7In order to start a dungeon you"
      - "&7need to unlock its dungeon key."
      - "&7These keys can be purchased"
      - "&7form the &cDungeon Master at /spawn"
      - "&7or at &nbuy.yourserver.com"
      - " "
      - "&7Once you have the key, you will"
      - "&7need to &ncraft a dungeon portal"
      - "&7each time you wish to run the dungeon."
  rewards:
    slot: 4
    item: "diamond"
    name: "&6&l&nDungeon Rewards"
    lore:
      - "&7You can obtain all kinds of"
      - "&7legendary treasures by defeating"
      - "&7dungeons, but most importantly"
      - "&7they allow you to obtain..."
      - " "
      - "&6&l*&r &7Heroic Enchantments"
      - "&6&l*&r &7Soul Trinkets"
      - "&6&l*&r &7Holy White Scrolls"
      - "&6&l*&r &7Dungeon Armor Sets"
      - "&6&l*&r &7Massive $/XP/mcMMO"
  tips:
    slot: 5
    item: "iron_fence"
    name: "&e&l&nDungeon Tips"
    lore:
      - "&7Server Dungeons opperate differently than"
      - "&7the normal of Server gameplay."
      - " "
      - "&e&l*&r &7You do &nNOT&r &7lose your inventory."
      - "&e&l*&r &7Every boss has custom mechanics."
      - "&e&l*&r &7If you do not strategize, you die."
      - "&e&l*&r &7Anyone can enter your dungeon portals."
      - "&e&l*&r &7Dungeons are PvP-enabled zones."
      - "&e&l*&r &7Server Dungeons are end-game"
      - "&7PvM content, they are HARD."
  portal event:
    slot: 13
    item: "nether_star"
    name: "&b&l&nDungeon Portal Event"
    lore:
      - " "
      - "&bNext Dungeon Portal spawns in..."
      - "&7{HRS} hours {MIN} minutes {SEC} seconds"
      - " "
      - "&7This portal opens at /spawn"
      - "&7next to the Dungeon Master."
  abandoned spaceship:
    slot: 20
    item: "mob_spawner"
    name: "&5&l&nAbandoned Spaceship"
    lore:
      - " "
      - "&5&lSTATUS"
      - "{STATUS}"
      - " "
      - "&5&lDIFFICULTY"
      - "&6&lGodly+"
      - " "
      - "&5&lLORE"
      - "&7A distress signal was receive from"
      - "&7an Intergalactic mining outpost a few"
      - "&7days ago in one of the most remote sectors"
      - "&7of the Servoverse."
      - " "
      - "&7You are being dispatched as part"
      - "&7of an elite team to respond to the"
      - "&7signal, neutralize any hostiles, and collect"
      - "&7the Server Ship log files."
      - " "
      - "&7... something about this mission does NOT feel right."
  21:
    slot: 21
    item: "{DUNGEON}"
  22:
    slot: 22
    item: "{DUNGEON}"
  23:
    slot: 23
    item: "{DUNGEON}"
  24:
    slot: 24
    item: "{DUNGEON}"
  29:
    slot: 29
    item: "key:Abandoned Spaceship"
  30:
    slot: 30
    item: "{KEY}"
  31:
    slot: 31
    item: "{KEY}"
  32:
    slot: 32
    item: "{KEY}"
  33:
    slot: 33
    item: "{KEY}"
#
custom items:
  dungeonportallootbox:
    item: "obsidian"
    name: "&5&lDungeon Portal&r &4&lLootbox"
    lore:
      - " "
      - "&7&nRight-click&r &7to receive one of the"
      - "&5&lDungeon Portal&r &7items listed below!"
      - " "
      - "&f&lRandom Loot (&r&7{REWARD_SIZE} item&f&l)"
      - " &f&l*&r &f{AMOUNT}x {ITEM}"
    reward size: 1
    rewards:
      - "enchantedobsidian;amount=8"
      - "fuelcell"
      - "dimensionweb"
      - "teleportationcrystal"
      - "interdimensionalcore"
      - "dungeonkey:ABANDONED_SPACESHIP;amount=2"
      - "dungeonkey:DESTROYED_OUTPOST;amount=2"
      - "dungeonportal:ABANDONED_SPACESHIP;amount=2"
      - "dungeonportal:DESTROYED_OUTPOST;amount=2"
  #
  dimensionweb:
    item: "web"
    name: "&6&lDimension Web"
    lore:
      - "&7A web of powerful arcane magic"
      - "&7that can be harnessed for instantaneous"
      - "&7interstellar /dungeon teleportation."
  enchantedobsidian:
    item: "obsidian"
    name: "&b&lEnchanted Obsidian"
    lore:
      - "&7Special obsidian used to construct"
      - "&7the infamous /dungeon portals."
  fuelcell:
    item: "redstone_torch_on"
    name: "&c&lServer Fuel Cell"
    lore:
      - "&7Next-Gen Servonaut space tech,"
      - "&7used to stabilize the output of"
      - "&7Dimension Webs for /dungeons."
  interdimensionalcore:
    item: "beacon"
    name: "&d&lInterdimensional Core"
    lore:
      - "&7A strange crystal emanating a powerful"
      - "&7ominous aura. You sense you will need other"
      - "&7components for this object to be useful"
      - "&7to you in your /dungeon runs."
  teleportationcrystal:
    item: "firework_charge"
    name: "&f&lTeleportation Crystal"
    lore:
      - "&7An indescent pulsating gem obtained"
      - "&7from the destroyed bridge of the"
      - "&7Abandoned Spaceship /dungeon. The"
      - "&7last remnant left by the servonauts"
      - "&7before they mysteriously vanished."
#