# Made by RandomHashTags
items:
  generator:
    item: "ender_chest"
    name: "&6&lMask Generator&r &7(Right Click)"
    lore:
    - " "
    - "&7Click to generate one of"
    - "&7the following player masks:"
    - " &6&l*&r &7Purge Mask"
    - " &6&l*&r &7Scarecrow Mask"
    - " &6&l*&r &7Turkey Mask"
    - " &6&l*&r &7Pilgrim Mask"
    - " &6&l*&r &7Monopoly Mask"
    - " &6&l*&r &7Necromancer Mask"
    - " &6&l*&r &7Santa Mask"
    - " &6&l*&r &7Reindeer Mask"
    - " &6&l*&r &7Party Hat Mask"
    - " &6&l*&r &7Death Knight Mask"
    - " &6&l*&r &7Rift Mask"
    - " &6&l*&r &7Lover Mask"
    - " &6&l*&r &7Glitch Mask"
    - " &6&l*&r &7Zeus Mask"
    - " &6&l*&r &7Bunny Mask"
    - " &6&l*&r &7Joker Mask"
    - " &6&l*&r &7Dungeon Mask"
    - " &6&l*&r &7Outpost Mask"
    - " &6&l*&r &7Stronghold Mask"
    - " &6&l*&r &7Boss Mask"
    can obtain:
      - "PURGE"
      - "SCARECROW"
      - "TURKEY"
      - "PILGRIM"
      - "MONOPOLY"
      - "NECROMANCER"
      - "SANTA"
      - "REINDEER"
      - "PARTY_HAT"
      - "DEATH_KNIGHT"
      - "RIFT"
      - "LOVER"
      - "GLITCH"
      - "ZEUS"
      - "BUNNY"
      - "JOKER"
    #
    received msg:
      - "&e&l(!)&r &e{PLAYER} has receive a &r{MASK}&r &efrom their Mask Generator!"
#
added lore:
  - " "
  - "&7&oAttach this mask to any helmet"
  - "&7&oto give it a visual override!"
  - " "
  - "&7To equip, place this mask on a helmet."
  - "&7To remove, right-click helmet with mask attached."
#