# Made by RandomHashTags
reveal item:
  item: "book"
  name: "&4&lMastery Enchantment Book &7(Right Click)"
  lore:
  - "&7Examine to receive a random"
  - "&4mastery &7enchantment book."
#
reveals enchant rarities: "MASTERY"
reveal enchant msg:
- "&e&l(!) &eYou examine the &4&lMastery Enchantment Book..."
- "&eand discovered {ENCHANT}"
#
revealed item:
  item: "book"
  name colors: "&4&l&n"
  apply colors: "&4"
  firework: "ball:red:fuchsia:4"
#
settings:
  success+destroy=100: false
  #
  success: "&a{PERCENT}% Success Rate"
  destroy: "&c{PERCENT}% Destroy Rate"
  lore format:
  - "{SUCCESS}"
  - "{DESTROY}"
  - "{ENCHANT_LORE}"
  - "{ENCHANT_TYPE}"
  - "&7Drop onto item to enchant"
#