# Made by RandomHashTags
messages:
  on cooldown:
    - "&c&l(!)&r &cThis pet is on cooldown! You can use its ability again in {TIME}."
#
settings:
  show graphic overlay cooldown: true
  exp:
    character: ":"
    character length: 50
    achieved color: "&a"
    unachieved color: "&c"
#
items:
  leash:
    item: "lead"
    name: "&6&lPet Leash"
    lore:
    - "&7Apply to an Inventory Pet"
    - "&7to keep it upon death!"
    applied lore: "&6&lLEASHED"
  rare candy:
    item: "red_mushroom"
    name: "&c&lRare Candy"
    lore:
    - "&7Magical candy imbued with"
    - "&7powerful growth hormones"
    - "&7for inventory pets."
    - " "
    - "&c&lAbility"
    - "&7Apply to any inventory pet to instantly"
    - "&7increase its level by +1 and trigger its"
    - "&7ability cooldown."
#
global attributes:
  - "BlackScrollUse;PlayerHasCombo=INVENTORY_PET_BLACKSCROLL;PlayerSetSuccessRate=rate+getPlayerCombo(INVENTORY_PET_BLACKSCROLL);PlayerComboStop=INVENTORY_PET_BLACKSCROLL"
  - "CustomEnchantApply;PlayerHasCombo=INVENTORY_PET_ENCHANTER;PlayerSetSuccess=rate+getPlayerCombo(INVENTORY_PET_ENCHANTER);PlayerComboStop=INVENTORY_PET_ENCHANTER"
  - "PlayerCommandPreprocess;PlayerIsInList=INVENTORY_PET_STRONGHOLD_SELL;cancelled=true;Command=/sh sell;SetAllowed=true"
  - "EntityDeath;KillerIsPlayer=true;KillerIsInList=INVENTORY_PET_XP_BOOSTER;SetDroppedExp=xp*getKillerCombo(INVENTORY_PET_XP_BOOSTER)"
  - "DepleteRarityGem;PlayerIsInList=INVENTORY_PET_TESLA;PlayerSetDepleteAmount=0"