# Made by RandomHashTags
reveal item:
  item: "book"
  name: "&6&lLegendary Enchantment Book &7(Right Click)"
  lore:
  - "&7Examine to receive a random"
  - "&6legendary &7enchantment book."
#
reveals enchant rarities: "LEGENDARY"
reveal enchant msg:
- "&e&l(!) &eYou examine the &6&lLegendary Enchantment Book..."
- "&eand discovered {ENCHANT}"
#
revealed item:
  item: "book"
  name colors: "&6&l&n"
  apply colors: "&6"
  firework: "ball:orange:fuchsia:2"
#
settings:
  success+destroy=100: false
  #
  success: "&a{PERCENT}% Success Rate"
  destroy: "&c{PERCENT}% Destroy Rate"
  lore format:
  - "{SUCCESS}"
  - "{DESTROY}"
  - "{ENCHANT_LORE}"
  - "{ENCHANT_TYPE}"
  - "&7Drop onto item to enchant"
#