# Made by RandomHashTags
messages:
  apply info:
  - "&e&l(!)&r &eTo apply this enchantment to an item, simply drag n' drop"
  - " &ethe book onto the item you'd like to enchant in your inventory!"
  - "&7The &bSuccess Rate &7is the chance of the book successfully being applied"
  - " &7to your equipment. The &bDestruction Chance &7is the percent chance of"
  - " &7your piece of equipment being &nDESTROYED&r &7if the book fails to apply."
  #
  apply potion effect:
  - "&b&l[+]&r &b{ENCHANT}: &7applying {POTION_EFFECT}"
  remove potion effect:
  - "&c&l[-]&r &c{ENCHANT}: &7removing {POTION_EFFECT}"
#
settings:
  enabled worlds:
    - "world"
    - "world_nether"
    - "world_the_end"
    - "koth"
    - "battle_royale"
  # If an item contains this lore, then enchants will not be able to be applied to it
  no more enchants:
    - "&7&lMax Custom Enchantments Reached"
  proc self harm: false
  # Required bow charging percent before enchants can proc from the bow. Default is 80.
  proc bow percent: 80
  # Proc enchants that are applied onto items other than their designated ones. Default is true.
  proc incorrect item: true
  # Removes the enchant from the item if the enchant cannot be applies to the item. Default is false.
  remove incorrect item: false
  # Removes the enchant from the item if the enchant is disabled. Default is false.
  remove disabled enchant: false
  # If the random enchant's level is zero, then don't apply the enchant. If false, it applies level 1.
  ## Mainly used for Gkits & Vkits
  level zero removal: true
  # Custom Enchants can only proc on these entities - used mostly for PvP and PvE events (PVA, ArrowHit, etc)
  ## CASE SENSITIVE | ALL UPPERCASE LETTERS
  can proc on: # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
    - "BAT"
    - "BLAZE"
    - "CAVE_SPIDER"
    - "CHICKEN"
    - "COD"
    - "COW"
    - "CREEPER"
    - "DOLPHIN"
    - "DONKEY"
    - "DROWNED"
    - "ELDER_GUARDIAN"
    - "ENDER_DRAGON"
    - "ENDERMAN"
    - "ENDERMITE"
    - "EVOKER"
    - "GHAST"
    - "GIANT"
    - "GUARDIAN"
    - "HORSE"
    - "HUSK"
    - "ILLUSIONER"
    - "IRON_GOLEM"
    - "LLAMA"
    - "MAGMA_CUBE"
    - "MULE"
    - "MUSHROOM_COW"
    - "OCELOT"
    - "PARROT"
    - "PHANTOM"
    - "PIG"
    - "PIG_ZOMBIE"
    - "PLAYER"
    - "POLAR_BEAR"
    - "PUFFERFISH"
    - "RABBIT"
    - "SALMON"
    - "SHEEP"
    - "SHULKER"
    - "SILVERFISH"
    - "SKELETON"
    - "SKELETON_HORSE"
    - "SLIME"
    - "SNOWMAN"
    - "SPIDER"
    - "SQUID"
    - "STRAY"
    - "TROPICAL_FISH"
    - "TURTLE"
    - "VEX"
    - "VILLAGER"
    - "VINDICATOR"
    - "WITCH"
    - "WITHER"
    - "WITHER_SKELETON"
    - "WITHER_SKULL"
    - "WOLF"
    - "ZOMBIE"
    - "ZOMBIE_HORSE"
    - "ZOMBIE_VILLAGER"
#
block break blacklist:
  global:
  - "bedrock"
  - "chest"
  - "ender_chest"
  - "obsidian"
  - "trapped_chest"
  pickaxe:
  - "dirt"
  - "grass"
  - "log"
  spade:
  - "stone"
  _axe:
  - "stone"
#
enchant types:
  helmet;chestplate;leggings;boots: "&7Armor Enchant"
  helmet: "&7Helmet Enchant"
  chestplate: "&7Chestplate Enchant"
  leggings: "&7Leggings Enchant"
  boots: "&7Boots Enchant"
  sword: "&7Sword Enchant"
  _axe: "&7Axe Enchant"
  sword;_axe: "&7Weapon Enchant"
  sword;_axe;bow: "&7Weapon Enchant"
  bow: "&7Bow Enchant"
  pickaxe: "&7Pickaxe Enchant"
  tool: "&7Tool Enchant"
  axe;spade;shears: "&7Tool Enchant"
#
entities:
  settings:
    default can target summoner: false
    default drops items upon death: false
  #
  guardian:
    type: IRON_GOLEM
    name: "&e{PLAYER}'s &9Guardian"
    attributes:
      - "addPotionEffect{[entity]strength:4:99999:false};addPotionEffect{[entity]absorption:4:99999:false};despawn{20*16}"
  spirit:
    type: BLAZE
    name: "&e{PLAYER}'s &9Spirit"
    attributes:
      - "addPotionEffect{[entity]regeneration:level:99999:false};despawn{20*18}"
  undead_ruse:
    type: ZOMBIE
    name: "&e{PLAYER}'s &bUndead Ruse"
    attributes:
      - "addPotionEffect{[entity]absorption:3:99999:false};addPotionEffect{[entity]fire_resistance:1:99999:false};addPotionEffect{[entity]speed:1:99999:false};despawn{20*20}"