# Made by RandomHashTags
settings:
  enabled: false
  name: "Dungeon Runner"
  completion: 1
  expiration: 86400
#
lore:
  - "&7Complete a Dungeon"
#
rewards:
  - "questtokens=2: 2x Quest Tokens"
#
trigger:
  - ""