# Made by RandomHashTags
settings:
  enabled: true
  name: "Elite Enchanter"
  completion: 60
  expiration: 86400
#
lore:
- "&7Purchase 60 Elite Books"
#
rewards:
- "questtokens=1: 1x Quest Tokens"
#
trigger:
- "EnchanterPurchase;isRarityBook;rarity=ELITE;+1"