# Made by RandomHashTags
settings:
  enabled: false
  name: "Ender Lord"
  completion: 1h30m
  expiration: 86400
#
lore:
- "&7Spend 1h 30m in The End"
#
rewards:
- "questtokens=2: 2x Quest Tokens"
#
trigger:
- ""