# Made by RandomHashTags
settings:
  enabled: true
  name: "Envoy Looter II"
  completion: 25
  expiration: 86400
#
lore:
- "&7Loot 25 Envoy Chests in a Day"
#
rewards:
- "questtokens=2: 2x Quest Tokens"
#
trigger:
- "EnvoyCrateLooted;cancelled=false;+1"