# Made by RandomHashTags
settings:
  enabled: true
  name: "Gambler III"
  completion: 1000
  expiration: 86400
#
lore:
- "&7Buy 1,000 Jackpot Tickets"
#
rewards:
- "questtokens=3: 3x Quest Tokens"
#
trigger:
- "JackpotPurchaseTickets;cancelled=false;PlayerIncreasePlayerQuest=GAMBLER_III:amount"