# Made by RandomHashTags
settings:
  enabled: false
  name: "KOTH Killer II"
  completion: 5
  expiration: 86400
#
lore:
- "&7Kill 5 players in KOTH arena"
#
rewards:
- "questtokens=2: 2x Quest Tokens"
#
trigger:
- "KilledPlayer;inKOTHWorld;+1"