# Made by RandomHashTags
settings:
  enabled: true
  name: "Legendary Looter"
  completion: 5
  expiration: 86400
#
lore:
- "&7Open 5 Legendary Chests"
#
rewards:
- "questtokens=3: 3x Quest Tokens"
#
trigger:
- "ServerCrateOpen;rarity=LEGENDARY;+1"