# Made by RandomHashTags
settings:
  name: "Master Miner"
  completion: 20000
  expiration: 86400
#
lore:
- "&7Mine 20,000 blocks with a pickaxe"
#
rewards:
- "questtokens=3: 3x Quest Tokens"
#
trigger:
- "BlockMined;material=_PICKAXE;+1"