# Made by RandomHashTags
settings:
  enabled: false
  name: "Mastery Kit Leveling"
  completion: 1
  expiration: 86400
#
lore:
  - "&7Tier up a /gkit to Tier 3"
#
rewards:
  - "questtokens=2: 2x Quest Tokens"
#
trigger:
  - "CustomKitLevelUp;KitType=GKIT_;toLevel=3;PlayerIncreasePQuest=MASTER_KIT_LEVELING:1"