# Made by RandomHashTags
settings:
  enabled: false
  name: "Novice Tinkerer"
  completion: 50
  expiration: 86400
#
lore:
- "&7Tinker 50 items"
#
rewards:
- "questtokens=1: 1x Quest Token"
#
trigger:
- ""