# Made by RandomHashTags
settings:
  name: "Quest Master"
  completion: 1
  expiration: 86400
#
lore:
- "&7Complete all other quests for the day"
#
rewards:
- "questtokens=3: 3x Quest Tokens"
#
trigger:
- "QuestCompleted;allQuestsAreCompleted;+1"