# Made by RandomHashTags
settings:
  enabled: true
  name: "Simple Enchanter"
  completion: 240
  expiration: 86400
#
lore:
- "&7Purchase 240 Simple Books"
#
rewards:
- "questtokens=1: 1x Quest Token"
#
trigger:
- "EnchanterPurchase;IsRarityBook=true;rarity=SIMPLE;PlayerIncreasePQuest=SIMPLE_ENCHANTER:1"