# Made by RandomHashTags
settings:
  enabled: false
  name: "Skill Booster III"
  completion: 5
  expiration: 86400
#
lore:
- "&7Successfully use 5 mcMMO Booster"
#
rewards:
- "questtokens=3: 3x Quest Tokens"
#
trigger:
- "ActivateBooster;booster=FACTION_MCMMO;PlayerIncreasePQuest=FACTION_MCMMO:1"