# Made by RandomHashTags
settings:
  enabled: false
  name: "Skill Booster I"
  completion: 1
  expiration: 86400
#
lore:
- "&7Successfully use 1 mcMMO Booster"
#
rewards:
- "questtokens=1: 1x Quest Token"
#
trigger:
- "ActivateBooster;nameContains=MCMMO;+1"