# Made by RandomHashTags
settings:
  enabled: true
  name: "Slaughter House III"
  completion: 25
  expiration: 86400
#
lore:
- "&7Kill 25 enemy faction players"
#
rewards:
- "questtokens=3: 3x Quest Tokens"
#
trigger:
- "KilledPlayer;isEnemy;+1"