# Made by RandomHashTags
settings:
  enabled: false
  name: "Stronghold Looter I"
  completion: 1
  expiration: 86400
#
lore:
- "&7Be the first to loot 1 Stronghold Chest"
#
rewards:
- "questtokens=1: 1x Quest Token"
#
trigger:
- "StronholdChestLooted;+1"