# Made by RandomHashTags
settings:
  enabled: true
  name: "Ultimate Looter"
  completion: 10
  expiration: 86400
#
lore:
- "&7Open 10 Ultimate Chests"
#
rewards:
- "questtokens=2: 2x Quest Tokens"
#
trigger:
- "ServerCrateOpen;rarity=ULTIMATE;+1"