# Made by RandomHashTags
settings:
  enabled: false
  name: "XP Boosted I"
  completion: 1
  expiration: 86400
#
lore:
- "&7Successfully use 1 XP Booster"
#
rewards:
- "questtokens=1: 1x Quest Token"
#
trigger:
- ""