# Made by RandomHashTags
settings:
  enabled: false
  name: "Item Customization"
  completion: 1
  expiration: 86400
#
lore:
  - "&7Use an Item Nametag"
#
rewards:
  - "questtokens=1: 1x Quest Token"
#
trigger:
  - "ItemNameTagUsed;cancelled=false;+1"