# Made by RandomHashTags
settings:
  enabled: true
  name: "Randomizer III"
  completion: 20
  expiration: 86400
#
lore:
  - "&7Use 20 Randomization Scrolls"
#
rewards:
  - "questtokens=3: 3x Quest Tokens"
#
trigger:
  - "RandomizationScrollUse;PlayerIncreasePQuest=RANDOMIZER_III:1"